### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by Smittyhead** [nigelheap/impartmedia-bookeasy-wordpress-plugin#5]
Hi, I'm getting the following when I try to activate your plugin

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /xxxx/xxxxxm/public_html/wp-content/plugins/bookeasy/api/import.php:53 Stack trace: #0 /xxxx/xxxxxm/public_html/wp-content/plugins/bookeasy/api/import.php(53): DateTimeZone->__construct('') #1 /xxxx/xxxxxm/public_html/wp-content/plugins/bookeasy/api/import.php(1016): BookeasyOperators_Import->__construct() #2 /xxxx/xxxxxm/public_html/wp-content/plugins/bookeasy/bookeasy.php(31): require_once('/xxxx/xxxxx...') #3 /xxxx/xxxxxm/public_html/wp-admin/includes/plugin.php(1897): include('/xxxx/xxxxx...') #4 /xxxx/xxxxxm/public_html/wp-admin/plugins.php(172): plugin_sandbox_scrape('bookeasy/bookea...') #5 {main} thrown in /xxxx/xxxxxm/public_html/wp-content/plugins/bookeasy/api/import.php on line 53

**Comment by Smittyhead** [comment]
Was able to an older version from my client then update the files that had changed and all seems to work fine.
